Fix for sequelize >5.19
Error: TypeError: sequelize.ValidationError is not a constructor
Solved importing class Sequelize and get constructor from there instead of sequelize (without capital)